_wandb:
    value:
        cli_version: 0.25.0
        e:
            z20aj68yo3omr9rhlue94nizrornd8t0:
                args:
                    - --march9_dir
                    - /home/amo/CINEMRI/data/ACDC/March9Data
                    - --training_dir
                    - /home/amo/CINEMRI/data/ACDC/training
                    - --n_patients
                    - "10"
                    - --epochs
                    - "3"
                    - --batch_size
                    - "4"
                    - --patience
                    - "5"
                    - --log_every
                    - "1"
                    - --cv
                    - kfold
                    - --n_splits
                    - "2"
                    - --wandb_project
                    - cardiac-ode
                    - --wandb_run_name
                    - smoke
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "105089261568"
                        used: "52691062784"
                email: Athena_1224@outlook.com
                executable: /home/amo/venv/bin/python
                git:
                    commit: e83fc6de4f90e5a4d421e74a5c123254b59c59f0
                    remote: git@github.com:chouathenamo/CINEMRI.git
                gpu: NVIDIA H100 NVL
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-a1b53955-65a1-8475-18b5-cc8979340688
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-6786bf66-cb62-254f-0df2-c8f7cd564739
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-20ca9ee4-2a58-e285-44b6-25be01a3ff09
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-28b7d1e7-6f24-bbf0-b75e-2efd08b1be31
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-a4d4f213-4805-13c1-53e9-1ff7d9368c5e
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-014b9cd9-4cf2-7edd-bb8e-fb44ee516dd3
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-034cdaa4-2051-9dfc-b0ae-69a9d48dc905
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-fc1d3563-b1a4-ac44-ed26-3e5e1997680b
                host: REDLRADADM35838
                memory:
                    total: "2164148867072"
                os: Linux-5.15.0-170-generic-x86_64-with-glibc2.35
                program: /home/amo/CINEMRI/src/train.py
                python: CPython 3.13.11
                root: /home/amo/CINEMRI
                startedAt: "2026-03-10T19:08:14.349332Z"
                writerId: z20aj68yo3omr9rhlue94nizrornd8t0
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.13.11
            "5": 0.25.0
            "10":
                - 20
            "12": 0.25.0
            "13": linux-x86_64
ablation:
    value: null
batch_size:
    value: 4
checkpoint_dir:
    value: checkpoints
cv:
    value: kfold
epochs:
    value: 3
log_every:
    value: 1
lr:
    value: 0.0001
march9_dir:
    value: /home/amo/CINEMRI/data/ACDC/March9Data
n_patients:
    value: 10
n_splits:
    value: 2
patience:
    value: 5
results_file:
    value: results.json
training_dir:
    value: /home/amo/CINEMRI/data/ACDC/training
wandb_project:
    value: cardiac-ode
wandb_run_name:
    value: smoke
